name: cicd

on:
  push:
    branches: [ "main", "dev" ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 코드 체크아웃
        uses: actions/checkout@v3

      - name: config.json에서 타겟 디렉토리 설정
        id: config-values
        run: |
          SPARK_DIR=$(jq -r '.SPARK_DIR' config.json)
          PYSPARK_CODE_DIR=$(jq -r '.PYSPARK_CODE_DIR' config.json)
          TARGET_DIR="${SPARK_DIR}/${PYSPARK_CODE_DIR}"
          echo "Setting TARGET_DIR: $TARGET_DIR"
          echo "target_dir=$TARGET_DIR" >> $GITHUB_OUTPUT
        shell: bash

      - name: 타겟 디렉토리 준비
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SCOUTER01_SSH_HOST }}
          username: ${{ secrets.SCOUTER01_SSH_USERNAME }}
          key: ${{ secrets.YUSU_SSH_KEY }}
          port: ${{ secrets.SCOUTER01_SSH_PORT }}
          script: |
            mkdir -p ${{ steps.config-values.outputs.target_dir }}
            rm -rf ${{ steps.config-values.outputs.target_dir }}/*

      - name: 저장소 코드 복사
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SCOUTER01_SSH_HOST }}
          username: ${{ secrets.SCOUTER01_SSH_USERNAME }}
          key: ${{ secrets.YUSU_SSH_KEY }}
          port: ${{ secrets.SCOUTER01_SSH_PORT }}
          source: "."
          target: ${{ steps.config-values.outputs.target_dir }}

      - name: Dockerfile 생성 및 디버깅, Spark 작업 배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SCOUTER01_SSH_HOST }}
          username: ${{ secrets.SCOUTER01_SSH_USERNAME }}
          key: ${{ secrets.YUSU_SSH_KEY }}
          port: ${{ secrets.SCOUTER01_SSH_PORT }}
          script: |
            cd ${{ steps.config-values.outputs.target_dir }}
            pwd
            ls
            chmod +x ./build-and-submit-spark.sh
            ./build-and-submit-spark.sh
